name: Secret Demo

on: [push]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando secret API_KEY
        run: |
          if [ -n "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY configurado."
          else
            echo "AVISO: O secret API_KEY não foi configurado no repositório."
          fi
